export const AUTH_API ='auth/'
export const REGISTER_API =AUTH_API + 'signup/'
export const LOGIN_API =AUTH_API + 'login/'
export const GOOGLE_LOGIN_API = AUTH_API + 'google/'
export const FORGOT_PASSWORD_API =AUTH_API + 'forgotcustomerPassword/'
export const RESET_PASSWORD_API =AUTH_API + 'resetPassword/'
