name: Deploy Next App

on:
  push:
    branches:
      - main # Change to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH command
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/client-test/bongoz/cineticket.antopolis.xyz # Navigate to your app directory on the server
            GIT_URL="https://x-access-token:${{ secrets.GIT_CREDENTIAL }}@github.com/The-Antopolis/client-bongoz-cineticket.com"
            git pull $GIT_URL main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            npm i --legacy-peer-deps
            # Install dependencies on the server
            # pm2 restart all # Restart your application using PM2 (or any other process manager you use)
            npm run build
            pm2 restart 22
